;; 指定したディレクトリの el ファイルを読み込む
(add-to-list 'load-path "~/.emacs.d/auto-install/")
(add-to-list 'load-path "~/.emacs.d/elisp/")
(add-to-list 'load-path "~/.emacs.d/auto-install/")
(add-to-list 'load-path "~/.emacs.d/elisp/csharp-mode/")
(add-to-list 'load-path "~/.emacs.d/elisp/haskell-mode/")
(add-to-list 'load-path "~/.emacs.d/plugins/sdic/")
(add-to-list 'load-path "~/.emacs.d/plugins/sdic/lisp/")
(add-to-list 'load-path "~/.emacs.d/plugins/yasnippet/")
(add-to-list 'load-path "~/.emacs.d/elisp/slime/")
(add-to-list 'load-path "~/.emacs.d/elisp/slime/contrib/")
(add-to-list 'load-path "~/.emacs.d/elisp/clojure-mode/")
(add-to-list 'load-path "~/.emacs.d/elisp/swank-clojure/")
(add-to-list 'load-path "~/.emacs.d/elisp/googlecl/")
(add-to-list 'load-path "~/.emacs.d/elisp/org-googlecl/")
(add-to-list 'load-path "~/.emacs.d/elisp/fsharp-mode/fsharp/")

(require 'cl)
(require 'saveplace)
(require 'init-loader)
(require 'uniquify)
(require 'recentf-ext)
(require 'auto-complete)
(init-loader-load "~/.emacs.d/inits")
